name: macrodynamics

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install project
        run: uv sync --all-groups
      - name: Lint the code
        run: uv run ruff format --check .
      - name: Run the tests
        run: uv run pytest
      - name: Build the docs
        run: uv run sphinx-build . docs/_build
